# Generated by Django 3.2.12 on 2022-02-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('num_entries', models.IntegerField()),
                ('x_mu', models.FloatField()),
                ('x_sigma', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotting.dataset')),
            ],
        ),
    ]
